### ISSUE TITLE
Broken Python package dependency: openshift version 0.13.0

### ISSUE THREAD

**Issue by haubenr** [ibm-s390-cloud/ocp-kvm-ipi-automation#9]
The Python package `openshift` is broken for version 0.13.0 - it cannot be installed:

```
pip3 install -U openshift
Collecting openshift
  Downloading https://files.pythonhosted.org/packages/12/1d/914bfdcc8e1e3b9b88b050d77b934146831b5fe320ae238e3e1813e40fa5/openshift-0.13.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fk8w5it6/openshift/setup.py", line 49, in <module>
        install_requires=extract_requirements('requirements.txt'),
      File "/tmp/pip-build-fk8w5it6/openshift/setup.py", line 36, in extract_requirements
        with open(filename, 'r') as requirements_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-fk8w5it6/openshift/
```

The playbooks need to exclude this specific package version until this has been resolved.

**Comment by haubenr** [comment]
Fixed by #11
